-- 코드를 입력하세요

WITH T AS (
SELECT P.PRODUCT_CODE,P.PRICE, SUM(O.SALES_AMOUNT) AS S FROM PRODUCT P 
INNER JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
)

SELECT PRODUCT_CODE, S*PRICE AS SALES FROM T ORDER BY SALES DESC, PRODUCT_CODE ASC






